### ISSUE TITLE
KDoc Theme not working

### ISSUE THREAD

**Issue by Medienbecken** [PhilippMundhenk/Kirby-BibTeX#4]
This plugin is not working with the KDoc Theme due to jquerry issues. I reported this as an issue at the Themes repo as well.

**Comment by PhilippMundhenk** [comment]
I can confirm this. The underlying system (https://github.com/vkaravir/bib-publication-list) uses the BibTex-0.1.2.js library, which in turn uses an older version of jquery. This clashes with some themes. If I manage to find the time. Probably not in the very near future though...

**Comment by PhilippMundhenk** [comment]
Fixed through new request by @ameeuw. New jQuery added. Please test with KDoc theme, should work better now.
