### ISSUE TITLE
Search Directory

### ISSUE THREAD

**Issue by sampaulp** [PhilippMundhenk/Kirby-BibTeX#5]
Bibtex: library.bib - When I add this tag , Kirby is looking for the library.bib file in the Kirby's home directory instead of the content directory. How to change this? I want Kirby to search for the .bib file in the content directory instead of the home directory. I don't want to give the path of the content folder as an attribute. 

Some Background:
Bibtex: content/library.bib -  When I add this one, Kirby is looking for the library.bib file in the Kirby's content directory. 

But the issue raises when a new library.bib file is added from the Panel, then the tag attribute changes into "Bibtex: library.bib" from "Bibtex: content/library.bib", so the Kirby starts looking for the .bib file in the home directory.

**Comment by PhilippMundhenk** [comment]
Not sure if I understand the last part: Why does the tag change to "Bibtex: library.bib" when you upload a file? And why do you not want to add "content/" in the tag?

I agree that the content/ part is rather redundant, as in Kirby, all content should be in that folder. However, changing to a different base path now might break compatibility with existing installations, if these update to a new version of the plugin. Users would need to adjust every page where the plugin is used, which is not ideal.

**Comment by sampaulp** [comment]
We have a functionality in our website, where the editors can choose which .bib file should be used from the available list of .bib files. Whenever the editor chooses a new .bib file from the drop down menu in the panel, the bibtex tag's attribute changes in the background. I can only give the file names in the drop down menu, not with the path. Thats why I didn't want to add "content/" in the tag. But now I had to remove the drop down option and the editor has to type in the .bib file name along with the path and it works. 

It would be better, if we cofigure the base path to the "/content" folder, after all Kirby's panel uploads all the files to its content folder. But if you think, it will lead to compatibility issues then we have to stick to this.

**Comment by PhilippMundhenk** [comment]
But why do you not simply extend the logic creating the bibtex tag and prepend the "content/" string to the selected filename? That should be a very easy solution.

**Comment by sampaulp** [comment]
Yes, I have exactly done and it is working. But what I wanted to mention is that, it would be better if the base path is content folder.
